kind: rabbitConfigLayout
version: udx.dev/rabbit-infra-config/v1

config:
  lifecycles:
    production:
      allow_subdirs: true

    staging:
      allow_subdirs: false

    development:
      allow_subdirs: true
