kind: rabbitConfigLayout
version: udx.dev/rabbit-infra-config/v1

config:
  lifecycles:
    production:
      allow_subdirs: true
      protected_only: true
      is_fallback: false

    staging:
      allow_subdirs: false
      protected_only: false
      is_fallback: false

    development:
      allow_subdirs: true
      protected_only: false
      is_fallback: true
